name: CI/CD Workflow

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
          cache: "maven"
          cache-dependency-path: "backend/pom.xml"
      - name: Build with Maven
        run: mvn clean install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - run: sam build
        working-directory: backend
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: backend
